/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData arrow_circle_o_left = const IconData(0xf11a, fontFamily: _kFontFam);
  static const IconData coffee = const IconData(0xf199, fontFamily: _kFontFam);
  static const IconData google = const IconData(0xf21a, fontFamily: _kFontFam);
  static const IconData info_circle = const IconData(0xf24b, fontFamily: _kFontFam);
  static const IconData instagram = const IconData(0xf24d, fontFamily: _kFontFam);
  static const IconData leaf = const IconData(0xf25c, fontFamily: _kFontFam);
  static const IconData music = const IconData(0xf299, fontFamily: _kFontFam);
  static const IconData paint_brush = const IconData(0xf2a7, fontFamily: _kFontFam);
  static const IconData paper_plane = const IconData(0xf2a8, fontFamily: _kFontFam);
  static const IconData pause = const IconData(0xf2ad, fontFamily: _kFontFam);
  static const IconData play = const IconData(0xf2be, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xf2eb, fontFamily: _kFontFam);
  static const IconData share_alt = const IconData(0xf2f1, fontFamily: _kFontFam);
  static const IconData step_backward = const IconData(0xf31e, fontFamily: _kFontFam);
  static const IconData step_forward = const IconData(0xf31f, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xf364, fontFamily: _kFontFam);
}
